languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Carter Pry"
logo = "img/c_logo.png"
description = ""
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "January 2, 2006"

[author]
  name = "Carter Pry"
  image = "img/carter.png"
  headline = "Hey, I'll be posting from time to time about projects or blogs"
  links = [
    { email = "mailto:contact@carterpry.com" },
    { github = "https://github.com/carterpry" },
    { linkedin = "https://linkedin.com/in/carter-pry" },
  ]
