[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
   name = "Tags"
   pageRef = "tags"
   weight = 20

[[main]]
  name = "About"
  pageRef = "about"
  weight = 30


# -- Footer Menu --


 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10
